# Numpy #

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. Check [this website](https://www.tutorialspoint.com/numpy/index.htm) for numpy tutorials.

In [1]:
import numpy as np

 **Question 1**: write a numpy program to convert a list of numeric value into a one-dimensional numpy array then create a 3x3 matrix

In [2]:
def list_2_numpy(listing:list) ->np.ndarray:
    '''
   Converting a list of numeric value into a one-dimensional numpy array then creating a 3x3 matrix and Printting it.
       Paramaters: 
           listing: a list contain 9 number
       Return: a 3 by 3 numpy array
   >>>list_2_numpy((range(1,10)))
   [[1 2 3]
    [4 5 6]
    [7 8 9]]
    '''
    matrix = np.array(listing).reshape(3,3)
    return matrix

In [3]:
assert (list_2_numpy(range(1,10)) == np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])).all() ,"assert list_2_numpy(range(1,10)) fails."

 **Question 2**:: write a numpy program to create a vector of size 10 and update sixth value to 11.

In [4]:
def change_vector() ->np.ndarray:
    '''
    Creating a vector of size 10 and update sixth value to 11.
    Paramater:None
    Print:the vector that the sixth value is 11
    >>>change_vector()
    [ 0  0  0  0  0  0 11  0  0  0]
    '''
    vector = np.linspace(0,0,10)
    vector[6] = 11
    return np.array(vector)

In [5]:
assert (change_vector() == np.array([0, 0, 0, 0, 0, 0, 11, 0, 0, 0])).all(),"assert change_vector fails."

 **Question 3**: write a numpy program to create an array with values ranging from 10 to 20 then reverse the array.

In [6]:
def reverse_array() ->np.ndarray:
    '''
    Creating an array with values ranging from 10 to 20 then reverse the array.
    Paramater:None
    Print:the array reversed array with values ranging from 10 to 20
    >>>reverse_array()
    [20 19 18 17 16 15 14 13 12 11 10]
    '''
    array = np.arange(10,21,1)
    m = list(array)
    m.reverse()
    n = np.array(m)
    return n

In [7]:
assert (reverse_array() == np.array([20,19,18,17,16,15,14,13,12,11,10])).all(),"assert reverse_array() fails."

 **Question 4**: write a numpy program to multiply the values of two given vectors.

In [8]:
def my_multiply(vector1:np.ndarray, vector2:np.ndarray) ->np.ndarray:
    '''
    Multiplying the values of every element of two given vectors.
    Paramater:
    vector1,vector2: any ndarray
    Return: product of inner element of above vectors 
    >>>my_multiply(np.array([1,3,5]), np.array([2,4,6]))
    [ 2 12 30]
    '''
    x = vector1*vector2
    return x

In [9]:
vector1 = np.array([1,3,5])
vector2 = np.array([2,4,6])
x = my_multiply(vector1, vector2)
assert (x == np.array([2,12,30])).all,"assert fails."

 **Question 5**: write a numpy program to calculate the dot product of two vectors.

In [10]:
def my_dot(vector1:np.ndarray, vector2:np.ndarray) ->int:
    '''
    Calculating the dot product of two vectors.
    Paramater:
    vector1,vector2: any ndarray
    Return: dot product
    >>>my_dot(np.array([1,3,5]), np.array([2,4,6]))
    44
    '''
    x = np.dot(vector1,vector2)
    return x

In [11]:
vector1 = np.array([1,3,5])
vector2 = np.array([2,4,6])
x = my_dot(vector1, vector2)
assert x == 44,"assert fails."

 **Question 6**: write a numpy program to calculate the cross product of two vectors.

In [12]:
def my_cross(vector1:np.ndarray, vector2:np.ndarray) ->np.ndarray:
    '''
    Calculating the cross product of two vectors.
    Paramater:
    vector1,vector2: any ndarray
    Returns: two cross products of different order of vectors
    >>>my_cross(np.array([1,3,5]), np.array([2,4,6]))
    (array([-2,  4, -2]), array([ 2, -4,  2]))
    '''
    result1 = np.cross(vector1, vector2)
    result2 = np.cross(vector2, vector1)
    return result1, result2

In [13]:
vector1 = np.array([1,3,5])
vector2 = np.array([2,4,6])
x = my_cross(vector1, vector2)
assert (x[0] == np.array([-2,4,-2])).all(),"assert result1 fails"
assert (x[1] == np.array([2,-4,2])).all(),"assert result2 fails."

 **Question 7**: write a numpy program to determine the intersection of two straight lines.Using .any() fuction judge the element of array weather is zero.

In [14]:
def is_intersection(a:tuple, b:tuple, c:tuple, d:tuple) ->bool:
    '''
    Determining the intersection of two straight lines.
    Paramaters: four points in space that doesn't coincide
    Return: if intersection
    >>>is_intersection((1,2,3), (0,1,2), (2,3,2), (0,0,0))
    False
    '''
    ab = np.array(a) - np.array(b)
    cd = np.array(c) - np.array(d)
    ad = np.array(a) - np.array(d)
    m = np.cross(ab,cd)
    n = np.dot(ad,m)
    return n == 0

In [15]:
x = is_intersection((1,2,3), (0,1,2), (2,3,2), (0,0,0))
assert x == False,"assert fails."

 **Question 8**: write a numpy program to compute the inverse of a given matrix.

In [16]:
def inverse_matrix(matrix:np.ndarray) ->np.ndarray:
    '''
    Computing the inverse of a given matrix.
    Paramater:any 2-dim square array
    Return: the inverse of above array
    >>>inverse_matrix(np.array([[1,0,0], [0,2,0], [0,0,4]]))
    [[1.   0.   0.  ]
    [0.   0.5  0.  ]
    [0.   0.   0.25]]
    '''
    return np.linalg.inv(matrix)

In [17]:
matrix = np.array([[1,0,0], [0,2,0], [0,0,4]])
x = inverse_matrix(matrix)
assert (x == np.array([[1,0,0],[0,0.5,0],[0,0,0.25]])).all(),"assert fails."

 **Question 9**: write a numpy program to compute the multiplication of two matrixes then compute the determinant of a given square array.

In [18]:
def mult_matrix(matrix1:np.ndarray, matrix2:np.ndarray) ->int:
    '''
    Computing the multiplication of two matrixes and compute the determinant of a given square array.
    Paramaters:
    matrix1,matrix2: any 2-dim square ndarray
    Return: the determinant of above result
    >>>mult_matrix(np.array([[1,0], [0,1]]), np.array([[2,3], [3,2]]))
    -5
    '''
    x = np.dot(matrix1,matrix2)
    return int(np.linalg.det(x))

In [19]:
matrix1 = np.array([[1,0], [0,1]])
matrix2 = np.array([[2,3], [3,2]])
x = mult_matrix(matrix1, matrix2)
assert x == -5,"assert fails."

 **Question 10**: write a numpy program to compute the rank, eigenvalues and eigenvectors of a given square matrix transpose.

In [2]:
def rank_eig(matrix:np.ndarray) ->(int, np.ndarray):
    '''
    Computing the rank, eigenvalues and eigenvectors of a given square matrix transpose.
    Paramater:matrix: any 2-dim square array
    Return :tuple contain int ,vector consisted eigenvalues and array consisted eigenvectors
    >>>rank_eig(np.array([[1,0,0], [0,1,0], [0,0,1]]))
    (3, array([1., 1., 1.]),
    array([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]]))
    '''
    matrix_ = matrix.T
    rank = np.linalg.matrix_rank(matrix_) # linear algebra
    eigenvalue,eigenvector = np.linalg.eig(matrix_)
    return rank,eigenvalue,eigenvector

In [4]:
matrix = np.array([[1,0,0], [0,1,0], [0,0,1]])
rank, eigenvalues, eigenvectors =  rank_eig(matrix)
assert rank == 3,"assert rank == 3 falis."
assert (eigenvalues == np.array([1, 1, 1])).all(),"assert eigenvalues == np.array([1, 1, 1]) fails."
assert (eigenvectors == np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])).all(),"assert (eigenvectors == np.array([1, 0, 0],[0, 1, 1],[0, 0, 1])).all() fails. "

 **Question 11**: write a numpy program to generate any random numbers from the normal distribution.

In [24]:
def normal(size:int) ->np.ndarray:
    '''
    Generating any random numbers from the normal distribution.
    Paramater:size:you want to generate the total of random numbers
    Return: random numbers from the normal distribution
    >>>normal(10)
    [ 1.09344946 -0.57605956 -0.4791958   0.39384737 -0.85581635  0.08555192
     -0.63934403 -0.92785404 -0.25639973 -1.53849967]
    '''
    return np.random.randn(size)

In [25]:
x = normal(10)
print(x)

[-0.21074627  0.52034712 -0.85091965  0.1785952  -0.42785533 -0.97653807
 -0.03327721  0.08934262  0.72441002 -0.47227818]


 **Question 12**: write a numpy program to simulate to flip coin.

In [26]:
def binomial(test_number:int, probability:float, size:int) ->np.ndarray:
    '''
    Generating any random numbers from the binomial distribution.
    Paramaters:
    test_number: frequency of testing
    probability: probability that the coin comes up heads
    size: quantity of output
    >>>binomial(10, 0.5, 10)
    [4 3 3 5 5 5 5 0 3 5]
    '''
    return np.random.binomial(test_number, probability, size)

In [27]:
x = binomial(10, 0.5, 10)
print(x)

[4 4 2 3 6 3 7 6 3 6]


 **Question 13**: write a numpy program to generate a array with random values.

In [28]:
def random_matrix(row, column):
    '''
    Generating a array with random values.
    Paramater: the row and colum of above random matrix
    Return: the matrix with random values
    >>>random_matrix(2,3)
    [[0.89840678 0.99005609 0.78972744]
    [0.6718429  0.56528883 0.33653837]]
    '''
    return np.random.rand(row,column)

In [29]:
x = random_matrix(2,3)
print(x)

[[0.67171152 0.48708878 0.06069042]
 [0.5155915  0.76248784 0.97168034]]


 **Question 14**: write a numpy program to simulate the relation among material, salary and yield

In [30]:
def covariance(material:np.ndarray, salary:np.ndarray, output:np.ndarray) ->np.ndarray:
    '''
    Calculating the covariance matrix.
    Paramaters:
    material,salary,output: 1dim array
    Return: matrix consisted convariance
    >>>covariance([10,20,15], [30,40,20], [20,30,25])
    [[ 25.  25.  25.]
     [ 25. 100.  25.]
     [ 25.  25.  25.]]
    '''
    return np.cov([material, salary,output])

In [31]:
material = np.array([10,20,15])
salary = np.array([30,40,20])
output = np.array([20,30,25])
x = covariance(material, salary, output)
print(x)

[[ 25.  25.  25.]
 [ 25. 100.  25.]
 [ 25.  25.  25.]]
